version: "3.4"
services:
  mysql:
    image: mariadb:10.4.20
    container_name: mysql
    restart: always
    ports:
      - "32000:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb.d/:/docker-entrypoint-initdb.d/
    env_file: .env
    privileged: true
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - internal_network

  backend:
    image: ${REGISTRY}/alub/backend
    container_name: backend
    volumes:
      - ./log:/log
    env_file: .env
    environment:
      SPRING_PROFILES_ACTIVE: "prod"
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/${MYSQL_DATABASE}?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true"
      server.address: 0.0.0.0
    depends_on:
      - mysql
    networks:
      - internal_network

  nginx:
    image: ${REGISTRY}/alub/nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    env_file: .env
    depends_on:
      - backend
      - certbot
    networks:
      - internal_network
    command: /bin/sh -c "while :; do sleep 6h & wait $${!}; nginx -s reload; done & envsubst '$${APP_DOMAIN}' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g \"daemon off;\""

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - internal_network
    
networks:
  internal_network:

volumes:
  mysql-data:
