name: Mirror to GitLab

on: [push]

jobs:
  mirror-to-gitlab:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Mirror to Gitlab
        uses: spyoungtech/mirror-action@master
        with:
          REMOTE: ${{ secrets.GITLAB_REPO }}
          GIT_USERNAME: ${{ secrets.GITLAB_ID }}
          GIT_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
